"use client";

import { Download, QrCode as QrIcon, RefreshCw } from "lucide-react";
import {
  useGenerateRefCodes,
  useRefCodes,
  type RefCodeRow,
} from "@/hooks/useAmbassadors";
import { Button } from "@/components/ui/Button";
import { Skeleton } from "@/components/ui/Skeleton";

/**
 * Educator ref codes + QR downloads. The QR encodes the /a/{shortCode}
 * scan-tracking URL, which redirects to /parent/signup?ref=CODE.
 */
export function RefCodesPanel({ role }: { role: string }) {
  const { data, isLoading } = useRefCodes(true);
  const generate = useGenerateRefCodes();
  const canGenerate = ["owner", "head_office", "admin"].includes(role);

  const download = (row: RefCodeRow, kind: "png" | "svg") => {
    const href =
      kind === "png"
        ? row.png
        : row.svg
          ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(row.svg)}`
          : undefined;
    if (!href) return;
    const a = document.createElement("a");
    a.href = href;
    a.download = `ambassador-qr-${row.user.name.replace(/\s+/g, "-").toLowerCase()}.${kind}`;
    a.click();
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-muted max-w-xl">
          Every educator and Director at a pilot centre gets a personal code
          and QR. Scans are counted, then families land on the sign-up page
          with the code attached.
        </p>
        {canGenerate && (
          <Button
            size="sm"
            variant="outline"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Generate missing codes
          </Button>
        )}
      </div>

      {isLoading ? (
        <Skeleton className="h-48 w-full" />
      ) : (data?.codes?.length ?? 0) === 0 ? (
        <div className="bg-card border border-border rounded-xl p-8 text-center text-sm text-muted">
          No codes yet.{" "}
          {canGenerate
            ? "Use “Generate missing codes” to create them for all pilot-centre staff."
            : "Ask your Director to generate them."}
        </div>
      ) : (
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {data!.codes.map((row) => (
            <div
              key={row.id}
              className="bg-card border border-border rounded-xl p-4 space-y-3"
            >
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0">
                  <p className="text-sm font-medium text-foreground truncate">
                    {row.user.name}
                  </p>
                  <p className="text-2xs text-muted truncate">
                    {row.user.service?.name ?? "—"}
                  </p>
                </div>
                {!row.active && (
                  <span className="text-2xs font-semibold px-1.5 py-0.5 rounded bg-surface text-muted border border-border">
                    Inactive
                  </span>
                )}
              </div>

              <div className="flex items-center gap-3">
                {row.svg ? (
                   
                  // need a true-white quiet zone to scan reliably, in dark
                  // mode included; bg-card would re-theme it away.
                  <div
                    className="w-20 h-20 shrink-0 rounded-lg overflow-hidden border border-border bg-white p-1 [&>svg]:w-full [&>svg]:h-full"
                    // Server-generated by the qrcode library from our own
                    // short-code URL — not user content.
                    dangerouslySetInnerHTML={{ __html: row.svg }}
                  />
                ) : (
                  <div className="w-20 h-20 shrink-0 rounded-lg border border-border bg-surface flex items-center justify-center">
                    <QrIcon className="w-8 h-8 text-muted" />
                  </div>
                )}
                <div className="min-w-0">
                  <p className="text-lg font-heading font-semibold tracking-widest text-brand">
                    {row.code}
                  </p>
                  <p className="text-2xs text-muted">
                    {row.scanCount} scan{row.scanCount === 1 ? "" : "s"}
                  </p>
                </div>
              </div>

              <div className="flex gap-2">
                <Button size="sm" variant="outline" onClick={() => download(row, "png")}>
                  <Download className="w-3.5 h-3.5" /> PNG
                </Button>
                <Button size="sm" variant="outline" onClick={() => download(row, "svg")}>
                  <Download className="w-3.5 h-3.5" /> SVG
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
