-- OSHC child detail fields. Additive + IF NOT EXISTS so a re-run is a no-op.
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "preferredName" TEXT;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "livesWith" TEXT;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "mainLanguageAtHome" TEXT;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "languagesOtherThanEnglish" TEXT;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "englishAssistance" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "indigenousStatus" TEXT;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "yearOfArrival" INTEGER;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "isStaffChild" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "suppressBirthdayPost" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "ownSunscreen" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "noAppPosting" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Child" ADD COLUMN IF NOT EXISTS "allowSocialMediaPost" BOOLEAN NOT NULL DEFAULT false;
