import { withAuth } from "next-auth/middleware";
import { NextResponse } from "next/server";
import type { Role } from "@prisma/client";

/**
 * Role-based page access map.
 * Duplicated from role-permissions.ts because middleware runs on the Edge
 * runtime and cannot import from Node-only modules (Prisma types are
 * fine because they are pure TS, but the file itself may pull in
 * non-edge-compatible deps). Keeping a thin copy here is intentional.
 */
const rolePageAccess: Record<string, string[]> = {
  owner: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/vision",
    "/rocks",
    "/todos",
    "/issues",
    "/scorecard",
    "/meetings",
    "/financials",
    "/performance",
    "/services",
    "/projects",
    "/tickets",
    "/marketing",
    "/marketing/email/compose",
    "/communication",
    "/compliance",
    "/compliance/templates",
    "/activity-library",
    "/documents",
    "/onboarding",
    "/timesheets",
    "/leave",
    "/contracts",
    "/team",
    "/settings",
    "/profile",
    "/crm",
    "/crm/templates",
    "/scenarios",
    "/data-room",
    "/reports/board",
    "/assistant",
    "/incidents",
    "/policies",
    "/holiday-quest",
    "/enquiries",
    "/enrolments",
    "/children",
    "/conversions",
    "/recruitment",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/audit-log",
    "/guides",
    "/help",
    "/directory",
    "/queue",
  ],
  head_office: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/vision",
    "/rocks",
    "/todos",
    "/issues",
    "/scorecard",
    "/meetings",
    "/financials",
    "/performance",
    "/services",
    "/projects",
    "/tickets",
    "/marketing",
    "/marketing/email/compose",
    "/communication",
    "/compliance",
    "/compliance/templates",
    "/activity-library",
    "/documents",
    "/onboarding",
    "/timesheets",
    "/leave",
    "/contracts",
    "/team",
    "/settings",
    "/profile",
    "/crm",
    "/crm/templates",
    "/scenarios",
    "/data-room",
    "/reports/board",
    "/assistant",
    "/incidents",
    "/policies",
    "/holiday-quest",
    "/enquiries",
    "/enrolments",
    "/children",
    "/conversions",
    "/recruitment",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/audit-log",
    "/guides",
    "/help",
    "/directory",
    "/queue",
  ],
  admin: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/vision",
    "/rocks",
    "/todos",
    "/issues",
    "/scorecard",
    "/meetings",
    "/financials",
    "/performance",
    "/services",
    "/projects",
    "/tickets",
    "/marketing",
    "/marketing/email/compose",
    "/communication",
    "/compliance",
    "/compliance/templates",
    "/activity-library",
    "/documents",
    "/onboarding",
    "/timesheets",
    "/leave",
    "/contracts",
    "/team",
    "/profile",
    "/crm",
    "/scenarios",
    "/data-room",
    "/reports/board",
    "/assistant",
    "/incidents",
    "/policies",
    "/holiday-quest",
    "/enquiries",
    "/enrolments",
    "/children",
    "/conversions",
    "/recruitment",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/audit-log",
    "/guides",
    "/help",
    "/directory",
    "/queue",
    "/settings",
    // No /crm/templates
  ],
  marketing: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/marketing",
    "/communication",
    "/crm",
    "/enquiries",
    "/conversions",
    "/projects",
    "/documents",
    "/profile",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/guides",
    "/help",
    "/directory",
    "/queue",
  ],
  coordinator: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/rocks",
    "/todos",
    "/issues",
    "/meetings",
    "/services",
    "/activity-library",
    "/communication",
    "/compliance",
    "/compliance/templates",
    "/documents",
    "/onboarding",
    "/profile",
    "/incidents",
    "/policies",
    "/holiday-quest",
    "/enquiries",
    "/enrolments",
    "/children",
    "/leave",
    "/timesheets",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/guides",
    "/help",
    "/directory",
    "/queue",
  ],
  member: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/rocks",
    "/todos",
    "/issues",
    "/meetings",
    "/services",
    "/activity-library",
    "/communication",
    "/compliance",
    "/compliance/templates",
    "/documents",
    "/onboarding",
    "/profile",
    "/incidents",
    "/policies",
    "/holiday-quest",
    "/enquiries",
    "/enrolments",
    "/children",
    "/leave",
    "/timesheets",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/guides",
    "/help",
    "/directory",
    "/queue",
  ],
  staff: [
    "/dashboard",
    "/getting-started",
    "/my-portal",
    "/activity-library",
    "/documents",
    "/communication",
    "/onboarding",
    "/todos",
    "/compliance",
    "/policies",
    "/profile",
    "/leave",
    "/tools/ccs-calculator",
    "/tools/the-amana-way",
    "/guides",
    "/help",
    "/directory",
    "/queue",
  ],
};

function canAccess(role: string, pathname: string): boolean {
  const allowed = rolePageAccess[role];
  if (!allowed) return false;
  return allowed.some(
    (path) => pathname === path || pathname.startsWith(path + "/")
  );
}

export default withAuth(
  function middleware(req) {
    const token = req.nextauth.token;
    const { pathname } = req.nextUrl;

    // Only enforce role checks on page routes (not API routes — those use requireAuth)
    if (pathname.startsWith("/api/")) {
      return NextResponse.next();
    }

    const role = token?.role as string | undefined;
    if (role && !canAccess(role, pathname)) {
      // Redirect to dashboard if user doesn't have access
      const url = req.nextUrl.clone();
      url.pathname = "/dashboard";
      return NextResponse.redirect(url);
    }

    return NextResponse.next();
  },
  {
    pages: {
      signIn: "/login",
    },
  }
);

export const config = {
  matcher: [
    "/dashboard/:path*",
    "/my-portal/:path*",
    "/vision/:path*",
    "/rocks/:path*",
    "/todos/:path*",
    "/issues/:path*",
    "/scorecard/:path*",
    "/meetings/:path*",
    "/financials/:path*",
    "/performance/:path*",
    "/team/:path*",
    "/settings/:path*",
    "/tickets/:path*",
    "/marketing/:path*",
    "/communication/:path*",
    "/services/:path*",
    "/projects/:path*",
    "/documents/:path*",
    "/compliance/:path*",
    "/onboarding/:path*",
    "/timesheets/:path*",
    "/leave/:path*",
    "/contracts/:path*",
    "/api/rocks/:path*",
    "/api/todos/:path*",
    "/api/issues/:path*",
    "/api/scorecard/:path*",
    "/api/users/:path*",
    "/api/marketing/:path*",
    "/api/communication/:path*",
    "/api/services/:path*",
    "/api/xero/:path*",
    "/api/health-scores/:path*",
    "/api/financials/:path*",
    "/api/performance/:path*",
    "/api/team/:path*",
    "/api/tickets/:path*",
    "/api/org-settings/:path*",
    "/api/attendance/:path*",
    "/api/compliance/:path*",
    "/api/notifications/:path*",
    "/api/accountability-chart/:path*",
    "/api/todo-templates/:path*",
    "/api/dashboard/:path*",
    "/api/leave/:path*",
    "/api/timesheets/:path*",
    "/api/timesheet-entries/:path*",
    "/api/contracts/:path*",
    "/policies/:path*",
    "/api/policies/:path*",
    "/api/offboarding/:path*",
    "/api/my-portal/:path*",
    "/api/emergency-contacts/:path*",
    "/api/qualifications/:path*",
    // ── Previously missing API routes (P0 security fix) ──
    "/api/documents/:path*",
    "/api/projects/:path*",
    "/api/project-templates/:path*",
    "/api/search/:path*",
    "/api/upload/:path*",
    "/api/email/:path*",
    "/api/activity-log/:path*",
    "/api/goals/:path*",
    "/api/vto/:path*",
    "/api/meetings/:path*",
    "/api/measurables/:path*",
    "/api/lms/:path*",
    "/api/onboarding/:path*",
    "/crm/:path*",
    "/api/crm/:path*",
    "/queue/:path*",
    "/api/queue/:path*",
    "/api/enrolments/:path*",
    "/enrolments/:path*",
    "/api/children/:path*",
    "/children/:path*",
    "/incidents/:path*",
    "/api/incidents/:path*",
    "/api/sequences/:path*",
    // ── Pages synced from role-permissions.ts ──
    "/getting-started/:path*",
    "/profile/:path*",
    "/conversions/:path*",
    "/recruitment/:path*",
    "/holiday-quest/:path*",
    "/tools/:path*",
    "/audit-log/:path*",
    "/guides/:path*",
    "/help/:path*",
    "/directory/:path*",
    "/enquiries/:path*",
    "/activity-library/:path*",
    "/scenarios/:path*",
    "/data-room/:path*",
    "/reports/:path*",
    "/assistant/:path*",
  ],
};
